### ISSUE TITLE
Syntax error needs to be fixed

### ISSUE THREAD

**Issue by peter279k** [00F100/fcphp-datasource#1]
According the following this line of code, the `return` seems to be duplicate and it should be removed.
https://github.com/00F100/fcphp-datasource/blob/0ac148e97d5f7bbb8ec3bfd051bc8421bc3d0b75/src/Datasource.php#L60

**Comment by 00F100** [comment]
Thank you for your help. This package is still under development, but will be ready soon.

**Comment by peter279k** [comment]
@00F100, thank you for your reply. Just create issue and let me know if possible :+1: .
